/******************************************************************************/
/*!
\file   M5ComponentTypes.h
\author Matt Casanova
\par    email: lazersquad\@gmail.com
\par    Mach5 Game Engine
\date   2016/08/10

This is an enumeration of all of the components in this game.
*/
/******************************************************************************/
#ifndef M5COMPONENT_TYPES_H
#define M5COMPONENT_TYPES_H
#include <string>

/*! Enumeration of your Game components.  This will get auto generated by
UserPreBuild.bat Each of the users stages will be added with the a CT_ in front
of the Component name.*/
enum M5ComponentTypes
{
	CT_GraphicsComponent,
	CT_INVALID
};

inline M5ComponentTypes StringToComponent(const std::string& /*string*/)
{
	return CT_INVALID;
}

#endif // M5COMPONENT_TYPES_H

