/******************************************************************************/
/*!
\file   M5StageTypes.h
\author Matt Casanova
\par    email: lazersquad\@gmail.com
\par    Mach5 Game Engine
\date   2016/08/10

This is an enumeration of all of the stages in this game.
*/
/******************************************************************************/
#ifndef M5STAGE_TYPES_H
#define M5STAGE_TYPES_H

/*! Enumeration of Your Game Stages.  This will get auto generated by 
UserPreBuild.bat Each of the users stages will be added with the a ST_ in front 
of the Stage name.*/
enum M5StageTypes
{
	ST_INVALID
};

#endif /*M5STAGE_TYPE_H*/