/******************************************************************************/
/*!
\file   M5ArcheTypes.h
\author Matt Casanova
\par    email: lazersquad\@gmail.com
\par    Mach5 Game Engine
\date   2016/08/23

This is an enumeration of all of the Archetypes in this game.
*/
/******************************************************************************/
#ifndef M5ARCHE_TYPES_H
#define M5ARCHE_TYPES_H

/*! Enumeration of Your Archetypes.  This will get auto generated by
UserPreBuild.bat Each of the users stages will be added with the a AT_ in front
of the file name.*/
enum M5ArcheTypes
{
	AT_INVALID
};

#endif //M5ARCHE_TYPES_H